### ISSUE TITLE
[BUG]: VelocityVanishAPI

### ISSUE THREAD

**Issue by SonnenPingu** [beanbeanjuice/SimpleProxyChat#140]
### Is there an existing issue for this?

- [X] I have searched the existing issues and not found ones relating to my problem.

### Version

newest build

### What proxy software are you seeing this issue on?

Velocity

### What proxy software version are you using?

neweste build 3.3 API

### Current Behaviour

lang.ClassNotFoundException: de.myzelyam.api.vanish.VelocityVanishAPI
        ... 8 more
[15:55:11 ERROR]: Exception in task com.beanbeanjuice.simpleproxychat.utility.listeners.velocity.VelocityVanishListener$$Lambda/0x00007f538cfcd4e8@54d8f65b by plugin SimpleProxyChat
java.lang.NoClassDefFoundError: de/myzelyam/api/vanish/VelocityVanishAPI
        at com.beanbeanjuice.simpleproxychat.utility.listeners.velocity.VelocityVanishListener.hasStateChange(VelocityVanishListener.java:23) ~[?:?]
        at com.beanbeanjuice.simpleproxychat.utility.listeners.velocity.VelocityVanishListener.lambda$checkStateChange$1(VelocityVanishListener.java:31) ~[?:?]
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[velocity.jar:3.3.0-SNAPSHOT (git-399bc232-b386)]
        at com.beanbeanjuice.simpleproxychat.utility.listeners.velocity.VelocityVanishListener.checkStateChange(VelocityVanishListener.java:30) ~[?:?]
        at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:285) ~[velocity.jar:3.3.0-SNAPSHOT (git-399bc232-b386)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassNotFoundException: de.myzelyam.api.vanish.VelocityVanishAPI
        ... 8 more
[15:55:11 ERROR]: Exception in task com.beanbeanjuice.simpleproxychat.utility.listeners.velocity.VelocityVanishListener$$Lambda/0x00007f538cfcd4e8@54d8f65b by plugin SimpleProxyChat
java.lang.NoClassDefFoundError: de/myzelyam/api/vanish/VelocityVanishAPI
        at com.beanbeanjuice.simpleproxychat.utility.listeners.velocity.VelocityVanishListener.hasStateChange(VelocityVanishListener.java:23) ~[?:?]
        at com.beanbeanjuice.simpleproxychat.utility.listeners.velocity.VelocityVanishListener.lambda$checkStateChange$1(VelocityVanishListener.java:31) ~[?:?]
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[velocity.jar:3.3.0-SNAPSHOT (git-399bc232-b386)]
        at com.beanbeanjuice.simpleproxychat.utility.listeners.velocity.VelocityVanishListener.checkStateChange(VelocityVanishListener.java:30) ~[?:?]
        at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:285) ~[velocity.jar:3.3.0-SNAPSHOT (git-399bc232-b386)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassNotFoundException: de.myzelyam.api.vanish.VelocityVanishAPI
        ... 8 more
[15:55:12 ERROR]: Exception in task com.beanbeanjuice.simpleproxychat.utility.listeners.velocity.VelocityVanishListener$$Lambda/0x00007f538cfcd4e8@54d8f65b by plugin SimpleProxyChat
java.lang.NoClassDefFoundError: de/myzelyam/api/vanish/VelocityVanishAPI
        at com.beanbeanjuice.simpleproxychat.utility.listeners.velocity.VelocityVanishListener.hasStateChange(VelocityVanishListener.java:23) ~[?:?]
        at com.beanbeanjuice.simpleproxychat.utility.listeners.velocity.VelocityVanishListener.lambda$checkStateChange$1(VelocityVanishListener.java:31) ~[?:?]
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[velocity.jar:3.3.0-SNAPSHOT (git-399bc232-b386)]
        at com.beanbeanjuice.simpleproxychat.utility.listeners.velocity.VelocityVanishListener.checkStateChange(VelocityVanishListener.java:30) ~[?:?]
        at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:285) ~[velocity.jar:3.3.0-SNAPSHOT (git-399bc232-b386)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassNotFoundException: de.myzelyam.api.vanish.VelocityVanishAPI
        ... 8 more
[15:55:12 ERROR]: Exception in task com.beanbeanjuice.simpleproxychat.utility.listeners.velocity.VelocityVanishListener$$Lambda/0x00007f538cfcd4e8@54d8f65b by plugin SimpleProxyChat
java.lang.NoClassDefFoundError: de/myzelyam/api/vanish/VelocityVanishAPI
        at com.beanbeanjuice.simpleproxychat.utility.listeners.velocity.VelocityVanishListener.hasStateChange(VelocityVanishListener.java:23) ~[?:?]
        at com.beanbeanjuice.simpleproxychat.utility.listeners.velocity.VelocityVanishListener.lambda$checkStateChange$1(VelocityVanishListener.java:31) ~[?:?]
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[velocity.jar:3.3.0-SNAPSHOT (git-399bc232-b386)]
        at com.beanbeanjuice.simpleproxychat.utility.listeners.velocity.VelocityVanishListener.checkStateChange(VelocityVanishListener.java:30) ~[?:?]
        at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:285) ~[velocity.jar:3.3.0-SNAPSHOT (git-399bc232-b386)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassNotFoundException: de.myzelyam.api.vanish.VelocityVanishAPI
        ... 8 more

### Steps to Reproduce

Download the new build and neu build velocity(API 3.3) 
And login..

### Are you certain this is a bug report?

- [X] I am certain this is a bug report, and not a feature request, improvement request, or a security vulnerability.

**Comment by beanbeanjuice** [comment]
Do you have premium vanish or supervanish installed?
