### ISSUE TITLE
[Improvement]: Allow a true/false option to disable or enable manage channel status

### ISSUE THREAD

**Issue by ZeLeAndroid** [beanbeanjuice/SimpleProxyChat#196]
### Is there an existing issue for this?

- [X] I have searched the existing issues and not found ones relating to my problem.

### Improvement

Love the plugin; In the server we use this for we do not allow bots to manage channels. With this the error pops up every so often:

`[13:53:36 ERROR]: Exception in task com.beanbeanjuice.simpleproxychat.SimpleProxyChatVelocity$$Lambda$554/0x0000000800f89048@49e300c by plugin SimpleProxyChat
com.beanbeanjuice.simpleproxychat.libs.net.dv8tion.jda.api.exceptions.InsufficientPermissionException: Cannot perform action due to a lack of Permission. Missing permission: MANAGE_CHANNEL
	at com.beanbeanjuice.simpleproxychat.libs.net.dv8tion.jda.internal.entities.channel.mixin.middleman.GuildChannelMixin.checkPermission(GuildChannelMixin.java:64) ~[?:?]
	at com.beanbeanjuice.simpleproxychat.libs.net.dv8tion.jda.internal.entities.channel.mixin.middleman.GuildChannelMixin.checkPermission(GuildChannelMixin.java:56) ~[?:?]
	at com.beanbeanjuice.simpleproxychat.libs.net.dv8tion.jda.internal.entities.channel.mixin.middleman.GuildChannelMixin.checkCanManage(GuildChannelMixin.java:71) ~[?:?]
	at com.beanbeanjuice.simpleproxychat.libs.net.dv8tion.jda.internal.managers.channel.ChannelManagerImpl.checkPermissions(ChannelManagerImpl.java:764) ~[?:?]
	at com.beanbeanjuice.simpleproxychat.libs.net.dv8tion.jda.internal.managers.channel.ChannelManagerImpl.<init>(ChannelManagerImpl.java:102) ~[?:?]
	at com.beanbeanjuice.simpleproxychat.libs.net.dv8tion.jda.internal.managers.channel.concrete.TextChannelManagerImpl.<init>(TextChannelManagerImpl.java:27) ~[?:?]
	at com.beanbeanjuice.simpleproxychat.libs.net.dv8tion.jda.internal.entities.channel.concrete.TextChannelImpl.getManager(TextChannelImpl.java:99) ~[?:?]
	at com.beanbeanjuice.simpleproxychat.discord.Bot.lambda$updateChannelTopic$6(Bot.java:141) ~[?:?]
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196) ~[?:?]
	at com.beanbeanjuice.simpleproxychat.discord.Bot.updateChannelTopic(Bot.java:140) ~[?:?]
	at com.beanbeanjuice.simpleproxychat.discord.Bot.channelUpdaterFunction(Bot.java:149) ~[?:?]
	at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:285) ~[BungeeCord.jar:3.3.0-SNAPSHOT (git-5154f029-b404)]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:833) [?:?]`

A simple setting in the main config to enable or disable this behavior would be appreciative.

### Are you certain this is a improvement request?

- [X] I am certain this is an improvement request, not a feature request, bug report, or security vulnerability report.

**Comment by beanbeanjuice** [comment]
Quick question; would you prefer a toggle or would you prefer it to only send one error message.

As an example, instead of that long error that was sent before, it will only ever send 1 error message during the startup, and it will say something like "No permission to manage channels. You can ignore this if you don't want the topic to be updated. This message won't be sent again."

That way, the config file can stay somewhat simple so that there aren't too many things in there.

**Comment by ZeLeAndroid** [comment]
I'm good with either, whatever is easier for you. Thank you for the quick response and amazing software.

**Comment by beanbeanjuice** [comment]
> I'm good with either, whatever is easier for you. Thank you for the quick response and amazing software.

Thank you so much! I'm glad to hear that. It always is nice to hear when working on these plugins!

This is an example of what would show;
![image](https://github.com/user-attachments/assets/c23ea05d-38e1-4c13-add3-460afae612b0)

I might do it this way that way not much setup will need to be done for the user-side of things. Thank you for bringing this to my attention! There should be an update out within a few hours.

**Comment by ZeLeAndroid** [comment]
Thank you, absolutely great with me. When I wake up tomorrow morning before work I'll look for the update and bring it on. I don't think I've ever seen such quick service and responses in any project. I'm about to head to work so you have a great rest of your day and thank you again.
